### ISSUE TITLE
Creating the converter to LHaloTrees from TreeFrog output

### ISSUE THREAD

**Issue by jacobseiler** [jacobseiler/genesis#1]
Initial issue message copied from the base fork.

@manodeep "Most of the work is already done by @jacobseiler, the last remaining bit is to account for flybys in the simulation. An implementation is [here](https://github.com/manodeep/ConvertCTrees/blob/master/convert_trees_to_lhalo.c#L1052-L1136)."

**Comment by jacobseiler** [comment]
The runtime of this will be ~8 hours for the test tree file.  Majority of this (confirmed with ``lineprof``) comes from the remapping of the old global IDs to the new forest-local IDs.  This is done using a ``for`` loop because you can't hash a Dictionary using an array.

I am unsure if this is avoidable in the current implementation.  There may exist a solution whereby we create a mapping dictionary for ALL forests first and then loop over the ``Snap_Keys`` once to fix up all the IDs.

**Comment by manodeep** [comment]
Looking through the commit history, will you please check if the "broken" flybys are now un-broken. And if this script is in tip-top shape, can we merge it back upstream?

**Comment by jacobseiler** [comment]
Just checked, Flybys are still broken.  Is the Tree format in `oz004` the 'accepted' format going forward? (I suppose we will have more confirmation on this tomorrow).   When the format's confirmed I'll update the defaults and clean-up before an upstream merge.

**Comment by manodeep** [comment]
Unclear if the current one is the correct one. As you said, we will find out tomorrow

**Comment by jacobseiler** [comment]
@manodeep Could you check the logic of `fix_nextprog()`, `fix_flybys()` and `fix_nextfof()` in `treefrog_to_lhalo.py`?  I've had a quick look at the first forest processed and it seems good.

(Actually I only checked the root snapshot for this forest and didn't check the entire forest to ensure `NextProgenitor` is 100% correct. Unsure how I'd do this properly [plus it's 11pm].)

**Comment by jacobseiler** [comment]
(Closing and moving discussion to [PR](https://github.com/manodeep/genesis/pull/2))
